
#define SUDOKU_SIZE 9
#define EMPTY_CASE 0

#define HORIZONTAL_BOLD_CHAR "\u2501"
#define HORIZONTAL_CHAR "\u2500"
#define VERTICAL_BOLD_CHAR "\u2503"
#define VERTICAL_CHAR "\u2502"

#define TOPLEFT_CORNER_CHAR "\u256D"
#define TOPRIGHT_CORNER_CHAR "\u256E"
#define BOTTOMLEFT_CORNER_CHAR "\u2570"
#define BOTTOMRIGHT_CORNER_CHAR "\u256F"

#define HORIZONTAL_VERTIVAL_DOWN_CHAR "\u2530"
#define HORIZONTAL_VERTIVAL_UP_CHAR "\u2538"

#define VERTIVAL_HORIZONTAL_RIGHT_CHAR "\u251D"
#define VERTIVAL_HORIZONTAL_LEFT_CHAR "\u2525"

#define CROSS "\u253C"
#define CROSS_BOLD "\u254B"

#define MAX_MSG_SIZE 100

#define BLUE_FG 44
#define BLUE_FG 44

typedef int t_grid[SUDOKU_SIZE][SUDOKU_SIZE];


