
#define SUDOKU_SIZE 9
#define EMPTY_CASE 0

#define MAX_MOVE 10

#define HORIZONTAL_BOLD_CHAR "\u2501"
#define HORIZONTAL_CHAR "\u2500"
#define VERTICAL_BOLD_CHAR "\u2503"
#define VERTICAL_CHAR "\u2502"

#define TOPLEFT_CORNER_CHAR "\u256D"
#define TOPRIGHT_CORNER_CHAR "\u256E"
#define BOTTOMLEFT_CORNER_CHAR "\u2570"
#define BOTTOMRIGHT_CORNER_CHAR "\u256F"

#define HORIZONTAL_VERTIVAL_DOWN_CHAR "\u252C"
#define HORIZONTAL_VERTIVAL_UP_CHAR "\u2534"

#define VERTIVAL_HORIZONTAL_RIGHT_CHAR "\u251C"
#define VERTIVAL_HORIZONTAL_LEFT_CHAR "\u2524"

#define CROSS "\u253C"
#define CROSS_BOLD "\u253F"

#define MAX_MSG_SIZE 500

#define BLUE_BG 44
#define BLUE_FG 34
#define YELLOW_BG 43
#define YELLOW_FG 33
#define GREEN_FG 32
#define RED_FG 31
#define FLASH_TEXT 5
#define WHITE_BG 37
#define WHITE_FG 47
#define BLACK_BG 40
#define BLACK_FG 30


typedef int t_grille[SUDOKU_SIZE][SUDOKU_SIZE];


